on:
  push:
    paths:
      - 'v2/**'
  pull_request:
    paths:
      - 'v2/**'

name: Test v2
jobs:
  test-nocache:
    if: "!startsWith(github.ref, 'refs/tags/')"
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: pull docker image
        run: docker pull docker.elastic.co/elasticsearch/elasticsearch:8.10.2
      - run: go test -p 1 ./...
        working-directory: v2